// Implementation file for parser generated by fsyacc
module SQLParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "SQLParser.fsy"
   
open Sql   

# 10 "SQLParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | ASC
  | DESC
  | SELECT
  | FROM
  | WHERE
  | ORDER
  | BY
  | JOIN
  | INNER
  | LEFT
  | RIGHT
  | ON
  | EQ
  | LT
  | LE
  | GT
  | GE
  | IS
  | ISNOT
  | COMMA
  | AND
  | OR
  | NULL
  | FLOAT of (float)
  | INT of (int)
  | ID of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_ASC
    | TOKEN_DESC
    | TOKEN_SELECT
    | TOKEN_FROM
    | TOKEN_WHERE
    | TOKEN_ORDER
    | TOKEN_BY
    | TOKEN_JOIN
    | TOKEN_INNER
    | TOKEN_LEFT
    | TOKEN_RIGHT
    | TOKEN_ON
    | TOKEN_EQ
    | TOKEN_LT
    | TOKEN_LE
    | TOKEN_GT
    | TOKEN_GE
    | TOKEN_IS
    | TOKEN_ISNOT
    | TOKEN_COMMA
    | TOKEN_AND
    | TOKEN_OR
    | TOKEN_NULL
    | TOKEN_FLOAT
    | TOKEN_INT
    | TOKEN_ID
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_columnList
    | NONTERM_joinList
    | NONTERM_joinClause
    | NONTERM_joinOnClause
    | NONTERM_conditionList
    | NONTERM_whereClause
    | NONTERM_op
    | NONTERM_value
    | NONTERM_orderByClause
    | NONTERM_orderByList
    | NONTERM_orderBy

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | ASC  -> 1 
  | DESC  -> 2 
  | SELECT  -> 3 
  | FROM  -> 4 
  | WHERE  -> 5 
  | ORDER  -> 6 
  | BY  -> 7 
  | JOIN  -> 8 
  | INNER  -> 9 
  | LEFT  -> 10 
  | RIGHT  -> 11 
  | ON  -> 12 
  | EQ  -> 13 
  | LT  -> 14 
  | LE  -> 15 
  | GT  -> 16 
  | GE  -> 17 
  | IS  -> 18 
  | ISNOT  -> 19 
  | COMMA  -> 20 
  | AND  -> 21 
  | OR  -> 22 
  | NULL  -> 23 
  | FLOAT _ -> 24 
  | INT _ -> 25 
  | ID _ -> 26 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_ASC 
  | 2 -> TOKEN_DESC 
  | 3 -> TOKEN_SELECT 
  | 4 -> TOKEN_FROM 
  | 5 -> TOKEN_WHERE 
  | 6 -> TOKEN_ORDER 
  | 7 -> TOKEN_BY 
  | 8 -> TOKEN_JOIN 
  | 9 -> TOKEN_INNER 
  | 10 -> TOKEN_LEFT 
  | 11 -> TOKEN_RIGHT 
  | 12 -> TOKEN_ON 
  | 13 -> TOKEN_EQ 
  | 14 -> TOKEN_LT 
  | 15 -> TOKEN_LE 
  | 16 -> TOKEN_GT 
  | 17 -> TOKEN_GE 
  | 18 -> TOKEN_IS 
  | 19 -> TOKEN_ISNOT 
  | 20 -> TOKEN_COMMA 
  | 21 -> TOKEN_AND 
  | 22 -> TOKEN_OR 
  | 23 -> TOKEN_NULL 
  | 24 -> TOKEN_FLOAT 
  | 25 -> TOKEN_INT 
  | 26 -> TOKEN_ID 
  | 29 -> TOKEN_end_of_input
  | 27 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_columnList 
    | 3 -> NONTERM_columnList 
    | 4 -> NONTERM_joinList 
    | 5 -> NONTERM_joinList 
    | 6 -> NONTERM_joinList 
    | 7 -> NONTERM_joinClause 
    | 8 -> NONTERM_joinClause 
    | 9 -> NONTERM_joinClause 
    | 10 -> NONTERM_joinOnClause 
    | 11 -> NONTERM_joinOnClause 
    | 12 -> NONTERM_conditionList 
    | 13 -> NONTERM_conditionList 
    | 14 -> NONTERM_conditionList 
    | 15 -> NONTERM_whereClause 
    | 16 -> NONTERM_whereClause 
    | 17 -> NONTERM_op 
    | 18 -> NONTERM_op 
    | 19 -> NONTERM_op 
    | 20 -> NONTERM_op 
    | 21 -> NONTERM_op 
    | 22 -> NONTERM_op 
    | 23 -> NONTERM_op 
    | 24 -> NONTERM_value 
    | 25 -> NONTERM_value 
    | 26 -> NONTERM_value 
    | 27 -> NONTERM_value 
    | 28 -> NONTERM_orderByClause 
    | 29 -> NONTERM_orderByClause 
    | 30 -> NONTERM_orderByList 
    | 31 -> NONTERM_orderByList 
    | 32 -> NONTERM_orderBy 
    | 33 -> NONTERM_orderBy 
    | 34 -> NONTERM_orderBy 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 29 
let _fsyacc_tagOfErrorTerminal = 27

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | ASC  -> "ASC" 
  | DESC  -> "DESC" 
  | SELECT  -> "SELECT" 
  | FROM  -> "FROM" 
  | WHERE  -> "WHERE" 
  | ORDER  -> "ORDER" 
  | BY  -> "BY" 
  | JOIN  -> "JOIN" 
  | INNER  -> "INNER" 
  | LEFT  -> "LEFT" 
  | RIGHT  -> "RIGHT" 
  | ON  -> "ON" 
  | EQ  -> "EQ" 
  | LT  -> "LT" 
  | LE  -> "LE" 
  | GT  -> "GT" 
  | GE  -> "GE" 
  | IS  -> "IS" 
  | ISNOT  -> "ISNOT" 
  | COMMA  -> "COMMA" 
  | AND  -> "AND" 
  | OR  -> "OR" 
  | NULL  -> "NULL" 
  | FLOAT _ -> "FLOAT" 
  | INT _ -> "INT" 
  | ID _ -> "ID" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | ASC  -> (null : System.Object) 
  | DESC  -> (null : System.Object) 
  | SELECT  -> (null : System.Object) 
  | FROM  -> (null : System.Object) 
  | WHERE  -> (null : System.Object) 
  | ORDER  -> (null : System.Object) 
  | BY  -> (null : System.Object) 
  | JOIN  -> (null : System.Object) 
  | INNER  -> (null : System.Object) 
  | LEFT  -> (null : System.Object) 
  | RIGHT  -> (null : System.Object) 
  | ON  -> (null : System.Object) 
  | EQ  -> (null : System.Object) 
  | LT  -> (null : System.Object) 
  | LE  -> (null : System.Object) 
  | GT  -> (null : System.Object) 
  | GE  -> (null : System.Object) 
  | IS  -> (null : System.Object) 
  | ISNOT  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | AND  -> (null : System.Object) 
  | OR  -> (null : System.Object) 
  | NULL  -> (null : System.Object) 
  | FLOAT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | INT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | ID _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 2us; 3us; 2us; 65535us; 5us; 6us; 13us; 14us; 2us; 65535us; 5us; 13us; 13us; 13us; 3us; 65535us; 17us; 18us; 21us; 22us; 25us; 26us; 4us; 65535us; 27us; 28us; 32us; 33us; 34us; 35us; 36us; 37us; 1us; 65535us; 6us; 7us; 1us; 65535us; 29us; 30us; 5us; 65535us; 27us; 29us; 30us; 31us; 32us; 29us; 34us; 29us; 36us; 29us; 1us; 65535us; 7us; 8us; 2us; 65535us; 50us; 51us; 53us; 54us; 2us; 65535us; 50us; 52us; 53us; 52us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 8us; 11us; 15us; 20us; 22us; 24us; 30us; 32us; 35us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 2us; 1us; 3us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 3us; 2us; 5us; 6us; 1us; 6us; 1us; 7us; 1us; 7us; 1us; 7us; 1us; 7us; 1us; 8us; 1us; 8us; 1us; 8us; 1us; 8us; 1us; 9us; 1us; 9us; 1us; 9us; 1us; 9us; 1us; 11us; 1us; 11us; 3us; 12us; 13us; 14us; 3us; 12us; 13us; 14us; 3us; 12us; 13us; 14us; 1us; 13us; 1us; 13us; 1us; 14us; 1us; 14us; 1us; 16us; 1us; 16us; 1us; 17us; 1us; 18us; 1us; 19us; 1us; 20us; 1us; 21us; 1us; 22us; 1us; 23us; 1us; 24us; 1us; 25us; 1us; 26us; 1us; 27us; 1us; 29us; 1us; 29us; 1us; 29us; 2us; 30us; 31us; 1us; 31us; 1us; 31us; 3us; 32us; 33us; 34us; 1us; 33us; 1us; 34us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 9us; 11us; 13us; 15us; 17us; 19us; 21us; 23us; 25us; 27us; 30us; 32us; 34us; 36us; 38us; 40us; 42us; 44us; 46us; 48us; 50us; 52us; 54us; 56us; 58us; 60us; 64us; 68us; 72us; 74us; 76us; 78us; 80us; 82us; 84us; 86us; 88us; 90us; 92us; 94us; 96us; 98us; 100us; 102us; 104us; 106us; 108us; 110us; 112us; 115us; 117us; 119us; 123us; 125us; |]
let _fsyacc_action_rows = 58
let _fsyacc_actionTableElements = [|1us; 32768us; 3us; 2us; 0us; 49152us; 1us; 32768us; 26us; 10us; 2us; 32768us; 4us; 4us; 20us; 11us; 1us; 32768us; 26us; 5us; 3us; 16388us; 9us; 15us; 10us; 19us; 11us; 23us; 1us; 16399us; 5us; 36us; 1us; 16412us; 6us; 49us; 1us; 32768us; 0us; 9us; 0us; 16385us; 0us; 16386us; 1us; 32768us; 26us; 12us; 0us; 16387us; 3us; 16388us; 9us; 15us; 10us; 19us; 11us; 23us; 0us; 16390us; 1us; 32768us; 8us; 16us; 1us; 32768us; 26us; 17us; 1us; 16394us; 12us; 27us; 0us; 16391us; 1us; 32768us; 8us; 20us; 1us; 32768us; 26us; 21us; 1us; 16394us; 12us; 27us; 0us; 16392us; 1us; 32768us; 8us; 24us; 1us; 32768us; 26us; 25us; 1us; 16394us; 12us; 27us; 0us; 16393us; 4us; 32768us; 23us; 48us; 24us; 46us; 25us; 45us; 26us; 47us; 0us; 16395us; 7us; 32768us; 13us; 38us; 14us; 39us; 15us; 40us; 16us; 41us; 17us; 42us; 18us; 43us; 19us; 44us; 4us; 32768us; 23us; 48us; 24us; 46us; 25us; 45us; 26us; 47us; 2us; 16396us; 21us; 32us; 22us; 34us; 4us; 32768us; 23us; 48us; 24us; 46us; 25us; 45us; 26us; 47us; 0us; 16397us; 4us; 32768us; 23us; 48us; 24us; 46us; 25us; 45us; 26us; 47us; 0us; 16398us; 4us; 32768us; 23us; 48us; 24us; 46us; 25us; 45us; 26us; 47us; 0us; 16400us; 0us; 16401us; 0us; 16402us; 0us; 16403us; 0us; 16404us; 0us; 16405us; 0us; 16406us; 0us; 16407us; 0us; 16408us; 0us; 16409us; 0us; 16410us; 0us; 16411us; 1us; 32768us; 7us; 50us; 1us; 32768us; 26us; 55us; 0us; 16413us; 1us; 16414us; 20us; 53us; 1us; 32768us; 26us; 55us; 0us; 16415us; 2us; 16416us; 1us; 56us; 2us; 57us; 0us; 16417us; 0us; 16418us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 2us; 3us; 5us; 8us; 10us; 14us; 16us; 18us; 20us; 21us; 22us; 24us; 25us; 29us; 30us; 32us; 34us; 36us; 37us; 39us; 41us; 43us; 44us; 46us; 48us; 50us; 51us; 56us; 57us; 65us; 70us; 73us; 78us; 79us; 84us; 85us; 90us; 91us; 92us; 93us; 94us; 95us; 96us; 97us; 98us; 99us; 100us; 101us; 102us; 104us; 106us; 107us; 109us; 111us; 112us; 115us; 116us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 8us; 1us; 3us; 0us; 1us; 2us; 4us; 4us; 4us; 0us; 2us; 3us; 5us; 5us; 0us; 2us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 0us; 3us; 1us; 3us; 1us; 2us; 2us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 3us; 3us; 4us; 4us; 4us; 5us; 5us; 6us; 6us; 6us; 7us; 7us; 8us; 8us; 8us; 8us; 8us; 8us; 8us; 9us; 9us; 9us; 9us; 10us; 10us; 11us; 11us; 12us; 12us; 12us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16385us; 16386us; 65535us; 16387us; 65535us; 16390us; 65535us; 65535us; 65535us; 16391us; 65535us; 65535us; 65535us; 16392us; 65535us; 65535us; 65535us; 16393us; 65535us; 16395us; 65535us; 65535us; 65535us; 65535us; 16397us; 65535us; 16398us; 65535us; 16400us; 16401us; 16402us; 16403us; 16404us; 16405us; 16406us; 16407us; 16408us; 16409us; 16410us; 16411us; 65535us; 65535us; 16413us; 65535us; 65535us; 16415us; 65535us; 16417us; 16418us; |]
let _fsyacc_reductions ()  =    [| 
# 267 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Sql.sqlStatement)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 276 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'columnList)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'joinList)) in
            let _6 = (let data = parseState.GetInput(6) in (Microsoft.FSharp.Core.Operators.unbox data : 'whereClause)) in
            let _7 = (let data = parseState.GetInput(7) in (Microsoft.FSharp.Core.Operators.unbox data : 'orderByClause)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "SQLParser.fsy"
                                                     
                                                     { Table = _4;   
                                                       Columns = List.rev _2;   
                                                       Joins = _5;   
                                                       Where = _6;   
                                                       OrderBy = _7 }   
                                                 
                   )
# 29 "SQLParser.fsy"
                 : Sql.sqlStatement));
# 297 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "SQLParser.fsy"
                                                   [_1]
                   )
# 37 "SQLParser.fsy"
                 : 'columnList));
# 308 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'columnList)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "SQLParser.fsy"
                                                  _3 :: _1 
                   )
# 38 "SQLParser.fsy"
                 : 'columnList));
# 320 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "SQLParser.fsy"
                                                           [] 
                   )
# 42 "SQLParser.fsy"
                 : 'joinList));
# 330 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'joinClause)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 "SQLParser.fsy"
                                                           [_1] 
                   )
# 43 "SQLParser.fsy"
                 : 'joinList));
# 341 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'joinClause)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'joinList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 44 "SQLParser.fsy"
                                                           _1 :: _2 
                   )
# 44 "SQLParser.fsy"
                 : 'joinList));
# 353 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'joinOnClause)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "SQLParser.fsy"
                                                           _3, Inner, _4 
                   )
# 47 "SQLParser.fsy"
                 : 'joinClause));
# 365 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'joinOnClause)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "SQLParser.fsy"
                                                           _3, Left, _4 
                   )
# 48 "SQLParser.fsy"
                 : 'joinClause));
# 377 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'joinOnClause)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "SQLParser.fsy"
                                                           _3, Right, _4 
                   )
# 49 "SQLParser.fsy"
                 : 'joinClause));
# 389 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "SQLParser.fsy"
                                                           None 
                   )
# 52 "SQLParser.fsy"
                 : 'joinOnClause));
# 399 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'conditionList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "SQLParser.fsy"
                                                           Some(_2) 
                   )
# 53 "SQLParser.fsy"
                 : 'joinOnClause));
# 410 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'op)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "SQLParser.fsy"
                                                               Cond(_1, _2, _3) 
                   )
# 56 "SQLParser.fsy"
                 : 'conditionList));
# 423 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'op)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'conditionList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "SQLParser.fsy"
                                                               And(Cond(_1, _2, _3), _5) 
                   )
# 57 "SQLParser.fsy"
                 : 'conditionList));
# 437 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'op)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'value)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'conditionList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 58 "SQLParser.fsy"
                                                               Or(Cond(_1, _2, _3), _5) 
                   )
# 58 "SQLParser.fsy"
                 : 'conditionList));
# 451 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 62 "SQLParser.fsy"
                                                           None 
                   )
# 62 "SQLParser.fsy"
                 : 'whereClause));
# 461 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'conditionList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 63 "SQLParser.fsy"
                                                           Some(_2) 
                   )
# 63 "SQLParser.fsy"
                 : 'whereClause));
# 472 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "SQLParser.fsy"
                              Eq 
                   )
# 65 "SQLParser.fsy"
                 : 'op));
# 482 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "SQLParser.fsy"
                                          Lt 
                   )
# 65 "SQLParser.fsy"
                 : 'op));
# 492 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "SQLParser.fsy"
                                                      Le 
                   )
# 65 "SQLParser.fsy"
                 : 'op));
# 502 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "SQLParser.fsy"
                                                                  Gt 
                   )
# 65 "SQLParser.fsy"
                 : 'op));
# 512 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "SQLParser.fsy"
                                                                              Ge 
                   )
# 65 "SQLParser.fsy"
                 : 'op));
# 522 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "SQLParser.fsy"
                                                                                          Is 
                   )
# 65 "SQLParser.fsy"
                 : 'op));
# 532 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "SQLParser.fsy"
                                                                                                        IsNot
                   )
# 65 "SQLParser.fsy"
                 : 'op));
# 542 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 68 "SQLParser.fsy"
                                                   Int(_1) 
                   )
# 68 "SQLParser.fsy"
                 : 'value));
# 553 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : float)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 69 "SQLParser.fsy"
                                                   Float(_1) 
                   )
# 69 "SQLParser.fsy"
                 : 'value));
# 564 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 70 "SQLParser.fsy"
                                                   String(_1) 
                   )
# 70 "SQLParser.fsy"
                 : 'value));
# 575 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 71 "SQLParser.fsy"
                                                  Null
                   )
# 71 "SQLParser.fsy"
                 : 'value));
# 585 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 76 "SQLParser.fsy"
                                                           [] 
                   )
# 76 "SQLParser.fsy"
                 : 'orderByClause));
# 595 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'orderByList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 77 "SQLParser.fsy"
                                                           _3 
                   )
# 77 "SQLParser.fsy"
                 : 'orderByClause));
# 606 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'orderBy)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 80 "SQLParser.fsy"
                                                           [_1] 
                   )
# 80 "SQLParser.fsy"
                 : 'orderByList));
# 617 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'orderBy)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'orderByList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 81 "SQLParser.fsy"
                                                           _1 :: _3 
                   )
# 81 "SQLParser.fsy"
                 : 'orderByList));
# 629 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 84 "SQLParser.fsy"
                                                           _1, Asc 
                   )
# 84 "SQLParser.fsy"
                 : 'orderBy));
# 640 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 85 "SQLParser.fsy"
                                                           _1, Asc 
                   )
# 85 "SQLParser.fsy"
                 : 'orderBy));
# 651 "SQLParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 86 "SQLParser.fsy"
                                                           _1, Desc
                   )
# 86 "SQLParser.fsy"
                 : 'orderBy));
|]
# 663 "SQLParser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 30;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : Sql.sqlStatement =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
